Add Flatiron Apprenticeship
FrancesCoronel/apprenticeships.me pull request #269
Opened 2021-01-06 17:01 UTC by changangus

Insert description of PR here

---

## ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Added my name to the bottom of the list under the **Credits** section in the `README.md` with a link to my website or GitHub profile 👥️

2021-01-07 02:16 UTC, benjaminmodayil requested changes
Hi @changangus  I left two comments for you. Let me know if I can help in any way. I would make these small changes for you if I could, but I don't have permissions to submit changes to other forks of the repo.

2021-01-07 02:16 UTC, benjaminmodayil commented on content/apprenticeships/Flatiron.md
> +link: "https://flatiron.com/"
Can you change this to a direct link to the listing or program? This is a link I found:
https://flatiron.com/careers/open-positions/2451150

2021-01-07 02:16 UTC, benjaminmodayil commented on content/apprenticeships/Flatiron.md
> +image: "/images/apprenticeships/flatiron.jpeg"
Can you update this `image` line to:

```
image: "flatiron.jpg" 
```

It seems I need to update the documentation as adding a path to the image isn't valid, but just the image name and extension is valid.

Also you had an "e" in your file extension when you have the file saved as `.jpg`

2021-01-07 22:37 UTC, changangus commented
Hey Ben,

Just made those changes, let me know if there is anything else that I might have missed!

2021-01-14 04:14 UTC, benjaminmodayil approved these changes

2021-01-14 04:14 UTC, benjaminmodayil commented
Looks good. Sorry for the late reply @changangus

2021-01-14 04:14 UTC, merged